/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: (typeof import('element-plus/es'))['ElAside']
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElCalendar: (typeof import('element-plus/es'))['ElCalendar']
    ElCard: (typeof import('element-plus/es'))['ElCard']
    ElCarousel: (typeof import('element-plus/es'))['ElCarousel']
    ElCarouselItem: (typeof import('element-plus/es'))['ElCarouselItem']
    ElCol: (typeof import('element-plus/es'))['ElCol']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDescriptions: (typeof import('element-plus/es'))['ElDescriptions']
    ElDescriptionsItem: (typeof import('element-plus/es'))['ElDescriptionsItem']
    ElDivider: (typeof import('element-plus/es'))['ElDivider']
    ElDrawer: (typeof import('element-plus/es'))['ElDrawer']
    ElHeader: (typeof import('element-plus/es'))['ElHeader']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElImage: (typeof import('element-plus/es'))['ElImage']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElInputNumber: (typeof import('element-plus/es'))['ElInputNumber']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElMenuItemGroup: (typeof import('element-plus/es'))['ElMenuItemGroup']
    ElOption: (typeof import('element-plus/es'))['ElOption']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    ElPopover: (typeof import('element-plus/es'))['ElPopover']
    ElRadio: (typeof import('element-plus/es'))['ElRadio']
    ElRadioButton: (typeof import('element-plus/es'))['ElRadioButton']
    ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElSelect: (typeof import('element-plus/es'))['ElSelect']
    ElSpace: (typeof import('element-plus/es'))['ElSpace']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTable: (typeof import('element-plus/es'))['ElTable']
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn']
    ElTableV2: (typeof import('element-plus/es'))['ElTableV2']
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane']
    ElTabs: (typeof import('element-plus/es'))['ElTabs']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    ElTimeline: (typeof import('element-plus/es'))['ElTimeline']
    ElTimelineItem: (typeof import('element-plus/es'))['ElTimelineItem']
    ElTour: (typeof import('element-plus/es'))['ElTour']
    ElTourStep: (typeof import('element-plus/es'))['ElTourStep']
    ElWatermark: (typeof import('element-plus/es'))['ElWatermark']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    HomeCom: (typeof import('./src/components/HomeCom.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: (typeof import('element-plus/es'))['ElLoadingDirective']
  }
}
